---
title: "MAS61002 Project Part B  \n Registration Number: 210138744"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(dplyr)
library(ggplot2)
data <- load("Data/E_PartB_data.RData")
```

# Question 1

# Question 1.1
```{r include=TRUE, results='asis',figures-side, fig.show="hold", out.width="50%"}
library(knitr) # for prettier tables
library(ggfortify) # so we can use fortify to create a datatable required for knitr
options(digits = 3) # let's keep output to sensible number of places
trialA <- q1dat %>% filter(drug == "A")
trialB <- q1dat %>% filter(drug == "B")

trialA.sv <- Surv(time=trialA$time, event=trialA$status, type="right")
trialASurv <- survfit(trialA.sv ~ 1, data = trialA)
tableA <- fortify(trialASurv)
# TODO NEED TO REName columns on table
print(kable(tableA))
summary(trialASurv)


trialB.sv <- Surv(time=trialB$time, event=trialB$status, type="right")
trialBSurv <- survfit(trialB.sv ~ 1, data = trialB)
tableB <- fortify(trialBSurv)
print(kable(tableB))

par(mar = c(4, 4, .1, .1))
plot(trialASurv, xlab ="months", ylab = "probablity of survival")
title("Kaplan-Meier  plot of trial A drug", line= -1 )
plot(trialBSurv, xlab ="months", ylab = "probablity of survival")
title( "Kaplan-Meier  plot of trial B drug", line= -1 )


```


# Question 1.2
Answer to Question 1.2 here

# Question 1.3
Answer to Question 1.3 here

# Question 2

# Question 2.1
Answer to Question 2.1 here

# Question 2.2
Answer to Question 2.2 here

# Question 2.3
Answer to Question 2.3 here

# Question 2.4
Answer to Question 2.4 here


